apiVersion: v1
kind: Service
metadata:
  labels:
    service: kafka
  name: kafka-srv
spec:
  selector:
    service: kafka
  ports:
    - name: internal
      port: 29092
      targetPort: 29092
    - name: external
      port: 9092
      targetPort: 9092
