apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-data-pvc1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: zookeeper-data-local-storage
  resources:
    requests:
      storage: 1Gi
