apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-log-pv1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: zookeeper-log-local-storage
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/zookeeper-log