apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-log-pvc1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: zookeeper-log-local-storage
  resources:
    requests:
      storage: 1Gi
